# Generated by Django 5.2.1 on 2025-07-15 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('images', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='comments.comments', verbose_name='родительский комментарий'),
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.post', verbose_name='статья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_comments', to=settings.AUTH_USER_MODEL, verbose_name='автор комментария'),
        ),
        migrations.AddField(
            model_name='likedislike',
            name='gallery_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_on_gallery_image', to='images.image'),
        ),
        migrations.AddField(
            model_name='likedislike',
            name='public_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_on_public_avatar', to='images.image'),
        ),
        migrations.AddField(
            model_name='likedislike',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='кто оценил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likedislike',
            name='user_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_on_user_avatar', to='images.image'),
        ),
        migrations.AddConstraint(
            model_name='likedislike',
            constraint=models.CheckConstraint(condition=models.Q(('user_avatar__isnull', False), ('public_avatar__isnull', False), ('gallery_image__isnull', False), _connector='OR'), name='at_least_one_target'),
        ),
        migrations.AddConstraint(
            model_name='likedislike',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user_avatar__isnull', False), ('public_avatar__isnull', False)), models.Q(('user_avatar__isnull', False), ('gallery_image__isnull', False)), models.Q(('public_avatar__isnull', False), ('gallery_image__isnull', False)), _connector='OR', _negated=True), name='only_one_target'),
        ),
        migrations.AddConstraint(
            model_name='likedislike',
            constraint=models.UniqueConstraint(fields=('user', 'user_avatar'), name='unique_user_avatar_like'),
        ),
        migrations.AddConstraint(
            model_name='likedislike',
            constraint=models.UniqueConstraint(fields=('user', 'public_avatar'), name='unique_public_avatar_like'),
        ),
        migrations.AddConstraint(
            model_name='likedislike',
            constraint=models.UniqueConstraint(fields=('user', 'gallery_image'), name='unique_gallery_image_like'),
        ),
    ]
