# Generated by Django 5.2.1 on 2025-07-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('is_private', models.BooleanField(default=False, verbose_name='приватный паблик')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'паблик',
                'verbose_name_plural': 'паблики',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PublicInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата приглашения')),
                ('accepted', models.BooleanField(default=None, null=True, verbose_name='принято')),
            ],
            options={
                'verbose_name': 'приглашение в паблик',
                'verbose_name_plural': 'приглашения в паблики',
                'ordering': ('created_at',),
            },
        ),
    ]
