# Generated by Django 5.2.1 on 2025-07-15 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_gallery_public_gallery_user_and_more'),
        ('publics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_avatar', to='images.image', verbose_name='аватар пользователя'),
        ),
        migrations.AddField(
            model_name='public',
            name='members',
            field=models.ManyToManyField(related_name='member_of_publics', to=settings.AUTH_USER_MODEL, verbose_name='участники'),
        ),
        migrations.AddField(
            model_name='public',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned_publics', to=settings.AUTH_USER_MODEL, verbose_name='владелец паблика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicinvite',
            name='invited_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invites_sent', to=settings.AUTH_USER_MODEL, verbose_name='кем приглашен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicinvite',
            name='invited_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invites_received', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicinvite',
            name='public',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='public_invites', to='publics.public', verbose_name='паблик'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='publicinvite',
            constraint=models.UniqueConstraint(fields=('public', 'invited_user', 'invited_by'), name='unique_public_invite'),
        ),
    ]
