# Generated by Django 5.2.1 on 2025-07-15 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('publics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='public',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_gallery', to='publics.public', verbose_name='паблик'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gallery', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('public__isnull', True)), models.Q(('user__isnull', True), ('public__isnull', False)), _connector='OR'), name='only_user_or_public'),
        ),
    ]
