# Generated by Django 5.2.1 on 2025-07-15 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group', models.BooleanField(default=False, verbose_name='групповой чат')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('is_group', False), models.Q(('is_group', True), ('title__isnull', False)), _connector='OR'), name='group_chat_requires_title')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='текст')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_message', to='chats.message', verbose_name='ответ на...')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('id',),
            },
        ),
    ]
